# Netlify Deploy
# 1. Confirm "build:netlify" command is included in themes/default/package.json
# 2. Set params.runTests: false in config/environments/netlify.yml

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
publish = "_site"
command = "npm run build"

[build.environment]
NODE_VERSION = "16.14.2"

# These two GIT_LFS variables need to be added to the project’s
# Deploy Settings in the Netlify UI, under Environment Variables:
# https://app.netlify.com/sites/<your-subdomain-here>/settings/deploys#environment
GIT_LFS_ENABLED = "true"
GIT_LFS_FETCH_INCLUDE = "*.jpeg,*.jpg,*.png,*.gif,*.epub,*.mobi,*.pdf,*.html"

# Settings for a `forthcoming` branch, which is just a static page
# They may also need to be cleared in the Netlify UI:
# https://app.netlify.com/sites/<your-subdomain-here>/settings/deploys#build-settings
[context.forthcoming]
publish = ""
command = ""
