analytics:
  googleId: 'GTM-NRDC63K'

bylineFormat: name # name | name-title | false

bibliography:
  displayOnPage: false
  displayShort: true
  heading: Bibliography

citations:
  divider: ', '
  popupStyle: text # text | icon

entryPage:
  sideBySide: true
  objectLinkText: View in Collection

epub:
  defaultCoverImage: 'cover-full.jpg'
  outputDir: '_epub'

footnotes:
  backlinkSymbol: '↩'

figures:
  assetDir: '/_assets/'
  enableModal: true
  imageDir: '/_assets/images'

licenseIcons: true

localization:
  defaultLocale: en-us

menuType: full # full | brief

navigation:
  nextButtonText: Next
  prevButtonText: Back

pageTitle:
  labelDivider: '. '

searchEnabled: true

tableOfContents:
  contributorDivider: ' — '

quire_credit_line: "This publication was created using Quire™, a multiformat publishing tool from Getty."